# Generated by Django 3.1.3 on 2021-01-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_on',
        ),
    ]
